WebApplication6/Controllers/FeaturedController.cs
using FireSharp.Interfaces;
using FireSharp.Response;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication6.Models;

namespace WebApplication6.Controllers
{
    public class FeaturedController : Controller
    {
        IFirebaseConfig config = new FireSharp.Config.FirebaseConfig
        {
            AuthSecret = "KEvOVZ7YYzeJfy2mFzA3Z2JxMhXQBkjyc1Z7RDuz",
            BasePath = "https://spotout-35ac6.firebaseio.com/"
        };
        IFirebaseClient client;
        // GET: Featured
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Basic()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Pro()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Enterprise()
        {
            return View();
        }

        private void AddFeaturedToFirebase(FeaturedBusiness featuredBusiness)
        {
            Users users = Session["vendorData"] as Users;
            featuredBusiness.phoneNo = users.phoneNo;
            client = new FireSharp.FirebaseClient(config);
            PushResponse response = client.Push("Featured/", featuredBusiness);
            featuredBusiness.featureID = response.Result.name;
            SetResponse setResponse = client.Set("Featured/" + featuredBusiness.featureID, featuredBusiness);
        }
    }
}

WebApplication6/Views/Featured/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Vendor | Prisolo</title>
    <!-- Css Styles -->
    <link rel="stylesheet" href="../Content/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
        .nav-item {
            background: 0;
        }
           .filterSearch .form-control{
            border-radius: 0;
        }
        .filterSearch a {
            margin-left: -35px;
            background: #eee;
            padding: 7px 10px;
        }


.pricing .card {
  border: none;
  border-radius: 1rem;
  transition: all 0.2s;
  box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
}

.pricing hr {
  margin: 1.5rem 0;
}

.pricing .card-title {
  margin: 0.5rem 0;
  font-size: 0.9rem;
  letter-spacing: .1rem;
  font-weight: bold;
}

.pricing .card-price {
  font-size: 2.5rem;
  margin: 0;
}

.pricing .card-price .period {
  font-size: 0.8rem;
}

.pricing ul li {
  margin-bottom: 1rem;
}

.pricing .text-muted {
  opacity: 0.7;
}

.pricing .btn {
  font-size: 80%;
  border-radius: 5rem;
  letter-spacing: .1rem;
  font-weight: bold;
  padding: 1rem;
  opacity: 0.7;
  transition: all 0.2s;
}
@@media (min-width: 992px) {
  .pricing .card:hover {
    margin-top: -.25rem;
    margin-bottom: .25rem;
    box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.3);
  }
  .pricing .card:hover .btn {
    opacity: 1;
  }
}
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <header>
        </header>
        <main>
            <div class="container">
                <div id="Plans_Pricing">
                    <section class="pricing py-5">
                        <div class="container">
                            <div class="text-center mb-4">
                                <h1><strong>Plans & Pricings</strong></h1>
                            </div>
                            <div class="row">
                                <!-- Free Tier -->
                                <div class="col-lg-4">
                                    <div class="card mb-5 mb-lg-0">
                                        <div class="card-body">
                                            <h5 class="card-title text-muted text-uppercase text-center">Basic</h5>
                                            <h6 class="card-price text-center">Rs600<span class="period">/50 Products</span></h6>
                                            <hr />
                                            <ul class="fa-ul">
                                                <li><strong>50 Products Available</strong></li>
                                            </ul>
                                            @*<form id="basicForm" action=@Html.ActionLink("Basic","Featured") method="post" />*@
                                            <div class="form-group">
                                                <p style="font-style:italic;font-family:'Segoe UI';font-weight:bold;margin-left: 868px;">@Html.ActionLink("Generate Report", "Report")</p>
                                            </div>
                                            @*@using (Html.BeginForm("Basic", "Featured", FormMethod.Post))
                                            {
                                                <button id="btnSubmitBasic" type="submit" value="Basic"></button>
                                            }*@
                                        </div>
                                    </div>
                                </div>
                                <!-- Plus Tier -->
                                <div class="col-lg-4">
                                    <div class="card mb-5 mb-lg-0">
                                        <div class="card-body">
                                            <h5 class="card-title text-muted text-uppercase text-center">Pro</h5>
                                            <h6 class="card-price text-center">Rs 1100<span class="period">/100 Products</span></h6>
                                            <hr />
                                            <ul class="fa-ul">
                                                <li><strong>100 Products Available</strong></li>
                                            </ul>
                                            <form action="@Url.Action("Pro")" method="post" />
                                            <div class="form-group">
                                                <input type="submit" value="Pro" class="btn btn-primary" />
                                            </div>
                                            @*@using (Html.BeginForm("Pro", "Featured", FormMethod.Post))
                                            {
                                                <button id="btnSubmitPro" type="submit" value="Pro"></button>
                                            }*@
                                        </div>
                                    </div>
                                </div>
                                <!-- Pro Tier -->                               
                                <div class="col-lg-4">
                                    <div class="card">
                                        <div class="card-body">
                                            <h5 class="card-title text-muted text-uppercase text-center">Enterprise</h5>
                                            <h6 class="card-price text-center">Rs 2000<span class="period">/200 products</span></h6>
                                            <hr />
                                            <ul class="fa-ul">
                                                <li><strong>2000 Products Available</strong></li>
                                            </ul>
                                            <form action="@Url.Action("Enterprise")" method="post" />
                                            <div class="form-group">
                                                <input type="submit" value="Enterprise" class="btn btn-primary" />
                                            </div>
                                            @*@using (Html.BeginForm("Enterprise", "Featured", FormMethod.Post))
                                            {
                                                <button id="btnSubmitEnterprise" type="submit" value="Enterprise"></button>
                                            }*@
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </main>
    </form>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="/Content/js/main.js"></script>
    <script>

    </script>
</body>
</html>