WebApplication6/Controllers/FeaturedController.cs
using FireSharp.Interfaces;
using FireSharp.Response;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication6.Models;

namespace WebApplication6.Controllers
{
    public class FeaturedController : Controller
    {
        IFirebaseConfig config = new FireSharp.Config.FirebaseConfig
        {
            AuthSecret = "KEvOVZ7YYzeJfy2mFzA3Z2JxMhXQBkjyc1Z7RDuz",
            BasePath = "https://spotout-35ac6.firebaseio.com/"
        };
        IFirebaseClient client;
        // GET: Featured
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Basic()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Pro()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Enterprise()
        {
            return View();
        }

        private void AddFeaturedToFirebase(FeaturedBusiness featuredBusiness)
        {
            Users users = Session["vendorData"] as Users;
            featuredBusiness.phoneNo = users.phoneNo;
            client = new FireSharp.FirebaseClient(config);
            PushResponse response = client.Push("Featured/", featuredBusiness);
            featuredBusiness.featureID = response.Result.name;
            SetResponse setResponse = client.Set("Featured/" + featuredBusiness.featureID, featuredBusiness);
        }
    }
}

WebApplication6/Controllers/VendorController.cs
using Firebase.Auth;
using Firebase.Storage;
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApplication6.Models;

namespace WebApplication6.Controllers
{
    public class VendorController : Controller
    {
        public static string Bucket = "spotout-35ac6.appspot.com";
        public static string authSecret = "KEvOVZ7YYzeJfy2mFzA3Z2JxMhXQBkjyc1Z7RDuz";        
        IFirebaseConfig config = new FireSharp.Config.FirebaseConfig
        {
            AuthSecret = "KEvOVZ7YYzeJfy2mFzA3Z2JxMhXQBkjyc1Z7RDuz",
            BasePath = "https://spotout-35ac6.firebaseio.com/"
        };
        IFirebaseClient client;
        // GET: Vendor
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(VendorProducts vendorProducts, HttpPostedFileBase file)
        {
            FileStream stream;
            
            try
            {
                if (file.ContentLength > 0)
                {
                    string path = Path.Combine(Server.MapPath("~/Content/images/"), file.FileName);
                    file.SaveAs(path);
                    stream = new FileStream(Path.Combine(path), FileMode.Open);
                    await Task.Run(() => fileUpload(stream, file.FileName));
                    vendorProducts.productimageName = file.FileName; 
                }
                AddUserToFirebase(vendorProducts);
                ModelState.AddModelError(string.Empty, "Added Successfully");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View();
        }

        private void AddUserToFirebase(VendorProducts vendorProducts)
        {
            Users users = Session["vendorData"] as Users;
            vendorProducts.phoneNo = users.phoneNo;
            client = new FireSharp.FirebaseClient(config);            
            PushResponse response = client.Push("Products/", vendorProducts);
            vendorProducts.id = response.Result.name;
            SetResponse setResponse = client.Set("Products/" + vendorProducts.id, vendorProducts);
        }

        //[HttpGet]
        //public ActionResult File()
        //{
            
        //    return View();
        //}

        //[HttpPost]
        //public async Task<ActionResult> File(Image image,HttpPostedFileBase file)
        //{
        //    FileStream stream;
        //    if (file.ContentLength > 0)
        //    {
        //        string path = Path.Combine(Server.MapPath("~/Content/images/"), file.FileName);
        //        file.SaveAs(path);
        //        stream = new FileStream(Path.Combine(path), FileMode.Open);
        //        await Task.Run(() => fileUpload(stream, file.FileName));

        //    }
        //        return View();
        //}

        public async void fileUpload(FileStream stream,string fileName)
        {
            //Users users = Session["vendorData"] as Users;
            var cancellation = new CancellationTokenSource();

            var task = new FirebaseStorage(
                Bucket,
                new FirebaseStorageOptions
                {
                    AuthTokenAsyncFactory = () => Task.FromResult(authSecret),
                    ThrowOnCancel = true // when you cancel the upload, exception is thrown. By default no exception is thrown
                })
                .Child("images")
                .Child(fileName)               
                .PutAsync(stream, cancellation.Token);

            try
            {
                string link = await task;
            }
            catch(Exception ex)
            {
                Console.WriteLine("Exception was Thrown: {0}", ex);
            }           
        }
        [HttpGet]
        public ActionResult Featured()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Featured(FeaturedBusiness featuredBusiness)
        {
            //try
            //{
            //    AddFeaturedToFirebase(featuredBusiness);
            //    ModelState.AddModelError(string.Empty, "Added Successfully");
            //}
            //catch (Exception ex)
            //{
            //    ModelState.AddModelError(string.Empty, ex.Message);
            //}

            return RedirectToAction("Index", "Featured");
            
        }

        private void AddFeaturedToFirebase(FeaturedBusiness featuredBusiness)
        {
            Users users = Session["vendorData"] as Users;
            featuredBusiness.phoneNo = users.phoneNo;
            client = new FireSharp.FirebaseClient(config);
            PushResponse response = client.Push("Featured/", featuredBusiness);
            featuredBusiness.featureID = response.Result.name;
            SetResponse setResponse = client.Set("Featured/" + featuredBusiness.featureID, featuredBusiness);
        }        
    }
}

WebApplication6/Views/Vendor/Create.cshtml
@model WebApplication6.Models.VendorProducts

@{
    ViewBag.Title = "Add Product";
}

    <h2>Add Product</h2>


@using (Html.BeginForm("Create","Vendor",FormMethod.Post, new { enctype = "multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>VendorProducts</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
   
    <div class="form-group">
        @Html.LabelFor(model => model.productTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.productDescp, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productDescp, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productDescp, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.productPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productPrice, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        Image
        <div class="col-md-10">
            <input type="file" class="form-control" name="file" accept="image/*" required />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add Product" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Featured Your Business", "Index","Featured")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication6/Views/Vendor/Featured.cshtml
@model WebApplication6.Models.FeaturedBusiness

@{
    Layout = null;
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Featured</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm("Featured","Vendor",FormMethod.Post, new { enctype = "multipart/form-data"}))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>FeaturedBusiness</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.featureID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.featureID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.featureID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.featureCategory, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.featureCategory, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.featureCategory, "", new { @class = "text-danger" })
                </div>
            </div>
           
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

WebApplication6/Views/Vendor/Index.cshtml
@model WebApplication6.Models.VendorLogin

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>